- name: Add the bitnami helm repo
  command: >
    helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Update helm repos
  command: >
    helm repo update

- name: helm install mariadb
  command: >
    helm install db bitnami/mariadb
        --namespace={{ namespace }}
        --set "auth.username={{ mysql_dbuser }},auth.password={{ mysql_password }},auth.database={{ mysql_dbname }},architecture=standalone,primary.persistence.enabled=false"
        --wait