- name: helm install registry
  command: >
    helm install ci/helm/schema-registry
        --debug
        --name schema-registry
        --set security.type={{ security }}
        --set namespace={{ namespace }}
        --set database={{ database }}
        --set image.tag={{ patchset }}
        --set image.repository={{ repository }}schema-registry
        --set-file security.caCertPath=ci/ssl/ca-cert
        --set-file security.caKeyPath=ci/ssl/ca-key
        --tiller-namespace={{ tiller_namespace }}
        --debug
        --wait
  args:
    chdir: "{{ srcdir }}"
