
- name: helm install schema-registry
  command: >
    helm install schema-registry ci/helm/schema-registry
        --debug
        --namespace={{ namespace }}
        --set security.type={{ security }}
        --set namespace={{ namespace }}
        --set database={{ database }}
        --set image.tag={{ patchset }}
        --set image.repository={{ repository }}schema-registry
        --set-file security.caCertPath=ci/ssl/ca-cert
        --set-file security.caKeyPath=ci/ssl/ca-key
        --debug
        --wait
  args:
    chdir: "{{ srcdir }}"

- name: list helm releases
  command: >
    helm list --namespace={{ namespace }} --debug

- name: list pods
  command: >
    kubectl get pods --namespace={{ namespace }}

- name: describe svcs
  command: >
    kubectl describe svc/schema-registry --namespace={{ namespace }}
