
- name: helm repo add
  command: >
    helm repo add DIM https://docker-registry.infra.cloudera.com:8443/helm/ --tiller-namespace={{ tiller_namespace }}
  args:
    chdir: "{{ srcdir }}"

- name: helm repo update
  command: >
    helm repo update --tiller-namespace={{ tiller_namespace }}
  args:
    chdir: "{{ srcdir }}"

- name: helm install registry
  command: >
    helm install DIM/schema-registry
        --debug
        --name schema-registry
        --set security.type={{ security }}
        --set namespace={{ namespace }}
        --set database={{ database }}
        --set image.tag={{ patchset }}
        --set image.repository={{ repository }}schema-registry
        --set-file security.caCertPath=ci/ssl/ca-cert
        --set-file security.caKeyPath=ci/ssl/ca-key
        --tiller-namespace={{ tiller_namespace }}
        --debug
        --wait
  args:
    chdir: "{{ srcdir }}"
