apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
spec:
  type: {{ .Values.service.type }}
{{ if eq .Values.security.type "kerberos" }}
  ports:
    - port: 8443
      targetPort: 8443
{{ else }}
  ports:
    - port: 9090
      targetPort: 9090
{{ end }}
  selector:
    app: {{ include "schema-registry.fullname" . }}-sr
