- hosts: all
  vars:
    srcdir: "{{ zuul.project.src_dir }}"
  tasks:
    - name: Run 'unit test'
      command: >
        ./gradlew
        --continue
        clean
        build -x test -x check -x javadoc
      args:
        chdir: "{{ srcdir }}"
