- name: Add the bitnami helm repo
  command: >
    helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Update helm repos
  command: >
    helm repo update

- name: helm install postgresql
  command: >
    helm install psql bitnami/postgresql
        --namespace={{ namespace }}
        --set postgresqlUsername=registry,postgresqlPassword=registry,postgresqlDatabase=registry,persistence.enabled=false
        --set "auth.username=registry,auth.password=registry,auth.database=registry,architecture=standalone,primary.persistence.enabled=false"
        --wait