- name: helm repo add DIM
  command: >
    helm repo add DIM https://docker-registry.infra.cloudera.com:8443/helm/ --tiller-namespace={{ tiller_namespace }}
  args:
    chdir: "{{ srcdir }}"

- name: helm repo update
  command: >
    helm repo update --tiller-namespace={{ tiller_namespace }}
  args:
    chdir: "{{ srcdir }}"

- name: helm install postgresql
  command: >
    helm install bitnami/postgresql
        --name psql
        --set postgresqlUsername=registry,postgresqlPassword=registry,postgresqlDatabase=registry,persistence.enabled=false
        --tiller-namespace={{ tiller_namespace }}
        --set "db.user=registry,db.password=registry,db.name=registry,replication.enabled=false,master.persistence.enabled=false"
        --version 8.6.4
        --wait
